# Generated by Django 4.2.2 on 2023-06-25 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z/d]{1,24}$', 'Should be started with a capital letter, min length 2 symb and max length - 25 symb')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Min value = 0')]),
        ),
    ]
